name: ECS Service Creation

on:
  workflow_dispatch:
    inputs:
      ecs-region:
        description: 'ECS region'
        default: "us-east-1"
        required: true
      ecs-service-name:
        description: 'ECS service name'
        required: true
      ecs-cluster-name:
        description: 'ECS cluster name'
        default: "lamp-prod"
        required: true
      ecs-task-definition-name:
        description: 'ECS task definition name'
        default: "lamp-prod"
        required: true
      subnet-id:
        description: 'Subnet ID for the network configuration'
        default: "subnet-004826a00b0f9af0e"
        required: true
      security-group-id:
        description: 'Security Group ID for the network configuration'
        default: "sg-0e7d8d3c05afb37b9"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ github.event.inputs.ecs-region }}

    - name: Create ECS Service
      run: |
        ecs_service_name=${{ github.event.inputs.ecs-service-name }}
        ecs_cluster_name=${{ github.event.inputs.ecs-cluster-name }}
        ecs_task_definition=${{ github.event.inputs.ecs-task-definition-name }}
        ecs_desired_count=1  # Set your desired count
        ecs_launch_type=FARGATE  # Change to EC2 if needed

        aws ecs create-service \
          --cluster $ecs_cluster_name \
          --service-name $ecs_service_name \
          --task-definition $ecs_task_definition \
          --desired-count $ecs_desired_count \
          --launch-type $ecs_launch_type \
          --network-configuration "awsvpcConfiguration={subnets=[$subnet_id],securityGroups=[$security_group_id],assignPublicIp=ENABLED}"
